version: '3.8'

services:
  gmail-poller:
    volumes:
      # For local development - use relative paths
      - ./credentials.json:/app/credentials.json:ro
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      # Override with local development paths
      - GMAIL_CREDENTIALS_FILE=/app/credentials.json
      - DATA_DIR=/app/data
      - LOG_DIR=/app/logs
      - OUTPUT_FILE=/app/data/emails.json