"""Initial migration

Revision ID: 0684cc85fbca
Revises: 
Create Date: 2025-10-31 10:18:20.898206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0684cc85fbca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.String(length=255), nullable=False),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('email_sender', sa.String(length=255), nullable=True),
    sa.Column('email_date', sa.DateTime(), nullable=True),
    sa.Column('polled_at', sa.DateTime(), nullable=True),
    sa.Column('loading_address', sa.Text(), nullable=False),
    sa.Column('unloading_address', sa.Text(), nullable=False),
    sa.Column('loading_date', sa.DateTime(), nullable=False),
    sa.Column('unloading_date', sa.DateTime(), nullable=False),
    sa.Column('loading_coordinates', sa.String(length=100), nullable=True),
    sa.Column('unloading_coordinates', sa.String(length=100), nullable=True),
    sa.Column('cargo_description', sa.Text(), nullable=False),
    sa.Column('weight', sa.String(length=100), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_email_id'), 'orders', ['email_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_email_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
