"""add_truck_id_to_driver

Revision ID: d1cf1f0207c1
Revises: a1b2c3d4e5f6
Create Date: 2025-11-27 16:56:04.334649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1cf1f0207c1'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('truck_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'drivers', 'trucks', ['truck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'truck_id')
    # ### end Alembic commands ###
