"""add route name remove driver

Revision ID: e2d3f4a5b6c7
Revises: d1cf1f0207c1
Create Date: 2025-11-28 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d3f4a5b6c7'
down_revision: Union[str, Sequence[str], None] = 'd1cf1f0207c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('name', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=True)
    op.drop_constraint('routes_driver_id_fkey', 'routes', type_='foreignkey')
    op.drop_column('routes', 'driver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('driver_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('routes_driver_id_fkey', 'routes', 'drivers', ['driver_id'], ['id'])
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_column('routes', 'name')
    # ### end Alembic commands ###
