version: '3.8'

services:
  email-processor:
    build:
      context: ../../services/email-processor
      dockerfile: Dockerfile
    container_name: fleet_email_processor
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data

  api-gateway:
    build:
      context: ../../services/api-gateway
      dockerfile: Dockerfile
    container_name: fleet_api_gateway
    restart: unless-stopped
    ports:
      - '8080:8080'

  ui:
    build:
      context: ../../services/ui
      dockerfile: Dockerfile
    container_name: fleet_ui
    restart: unless-stopped
    ports:
      - '3000:3000'
