version: '3.8'

services:
  # Email Processing Service - Production Ready
  email-processor:
    image: ghcr.io/valkozaur/email-poller:latest
    container_name: email-poller
    restart: unless-stopped
    env_file:
      - /opt/fleetmanager/.env.production
    volumes:
      # Persist data and tokens
      - email_poller_data:/app/data
      - email_poller_logs:/app/logs
      # Mount credentials securely
      - /opt/fleetmanager/credentials:/app/credentials:ro
    environment:
      - DATA_DIR=/app/data
      - GMAIL_CREDENTIALS_FILE=/app/credentials/credentials.json
    mem_limit: 512m
    mem_reservation: 256m
    cpus: 1.0
    healthcheck:
      test: ["CMD-SHELL", "test -f /app/credentials/credentials.json || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - fleetmanager-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  email_poller_data:
    driver: local
  email_poller_logs:
    driver: local

networks:
  fleetmanager-network:
    driver: bridge
